<?php

declare(strict_types=1);

namespace OpenEmail\Constants;

final class Languages
{
    public const ALL = [
        ['code' => 'en', 'label' => 'English', 'native' => 'English', 'flag' => '🇬🇧', 'rtl' => false],
        ['code' => 'es', 'label' => 'Spanish', 'native' => 'Español', 'flag' => '🇪🇸', 'rtl' => false],
        ['code' => 'zh-Hans', 'label' => 'Simplified Chinese', 'native' => '简体中文', 'flag' => '🇨🇳', 'rtl' => false],
        ['code' => 'zh-Hant', 'label' => 'Traditional Chinese', 'native' => '繁體中文', 'flag' => '🇹🇼', 'rtl' => false],
        ['code' => 'hi', 'label' => 'Hindi', 'native' => 'हिन्दी', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'ar', 'label' => 'Arabic', 'native' => 'العربية', 'flag' => '🇸🇦', 'rtl' => true],
        [
            'code' => 'pt-BR',
            'label' => 'Brazilian Portuguese',
            'native' => 'Português (Brasil)',
            'flag' => '🇧🇷',
            'rtl' => false,
        ],
        ['code' => 'pt', 'label' => 'Portuguese', 'native' => 'Português', 'flag' => '🇵🇹', 'rtl' => false],
        ['code' => 'fr', 'label' => 'French', 'native' => 'Français', 'flag' => '🇫🇷', 'rtl' => false],
        ['code' => 'de', 'label' => 'German', 'native' => 'Deutsch', 'flag' => '🇩🇪', 'rtl' => false],
        ['code' => 'ru', 'label' => 'Russian', 'native' => 'Русский', 'flag' => '🇷🇺', 'rtl' => false],
        ['code' => 'ja', 'label' => 'Japanese', 'native' => '日本語', 'flag' => '🇯🇵', 'rtl' => false],
        ['code' => 'ko', 'label' => 'Korean', 'native' => '한국어', 'flag' => '🇰🇷', 'rtl' => false],
        ['code' => 'it', 'label' => 'Italian', 'native' => 'Italiano', 'flag' => '🇮🇹', 'rtl' => false],
        ['code' => 'nl', 'label' => 'Dutch', 'native' => 'Nederlands', 'flag' => '🇳🇱', 'rtl' => false],
        ['code' => 'tr', 'label' => 'Turkish', 'native' => 'Türkçe', 'flag' => '🇹🇷', 'rtl' => false],
        ['code' => 'pl', 'label' => 'Polish', 'native' => 'Polski', 'flag' => '🇵🇱', 'rtl' => false],
        ['code' => 'uk', 'label' => 'Ukrainian', 'native' => 'Українська', 'flag' => '🇺🇦', 'rtl' => false],
        ['code' => 'vi', 'label' => 'Vietnamese', 'native' => 'Tiếng Việt', 'flag' => '🇻🇳', 'rtl' => false],
        ['code' => 'id', 'label' => 'Indonesian', 'native' => 'Bahasa Indonesia', 'flag' => '🇮🇩', 'rtl' => false],
        ['code' => 'th', 'label' => 'Thai', 'native' => 'ไทย', 'flag' => '🇹🇭', 'rtl' => false],
        ['code' => 'sv', 'label' => 'Swedish', 'native' => 'Svenska', 'flag' => '🇸🇪', 'rtl' => false],
        ['code' => 'da', 'label' => 'Danish', 'native' => 'Dansk', 'flag' => '🇩🇰', 'rtl' => false],
        ['code' => 'no', 'label' => 'Norwegian', 'native' => 'Norsk', 'flag' => '🇳🇴', 'rtl' => false],
        ['code' => 'fi', 'label' => 'Finnish', 'native' => 'Suomi', 'flag' => '🇫🇮', 'rtl' => false],
        ['code' => 'cs', 'label' => 'Czech', 'native' => 'Čeština', 'flag' => '🇨🇿', 'rtl' => false],
        ['code' => 'el', 'label' => 'Greek', 'native' => 'Ελληνικά', 'flag' => '🇬🇷', 'rtl' => false],
        ['code' => 'he', 'label' => 'Hebrew', 'native' => 'עברית', 'flag' => '🇮🇱', 'rtl' => true],
        ['code' => 'ro', 'label' => 'Romanian', 'native' => 'Română', 'flag' => '🇷🇴', 'rtl' => false],
        ['code' => 'hu', 'label' => 'Hungarian', 'native' => 'Magyar', 'flag' => '🇭🇺', 'rtl' => false],
        ['code' => 'bn', 'label' => 'Bengali', 'native' => 'বাংলা', 'flag' => '🇧🇩', 'rtl' => false],
        ['code' => 'ur', 'label' => 'Urdu', 'native' => 'اردو', 'flag' => '🇵🇰', 'rtl' => true],
        ['code' => 'fa', 'label' => 'Persian', 'native' => 'فارسی', 'flag' => '🇮🇷', 'rtl' => true],
        ['code' => 'ms', 'label' => 'Malay', 'native' => 'Bahasa Melayu', 'flag' => '🇲🇾', 'rtl' => false],
        ['code' => 'ta', 'label' => 'Tamil', 'native' => 'தமிழ்', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'ca', 'label' => 'Catalan', 'native' => 'Català', 'flag' => '🇦🇩', 'rtl' => false],
        [
            'code' => 'en-GB',
            'label' => 'British English',
            'native' => 'English (United Kingdom)',
            'flag' => '🇬🇧',
            'rtl' => false,
        ],
        [
            'code' => 'en-US',
            'label' => 'American English',
            'native' => 'English (United States)',
            'flag' => '🇺🇸',
            'rtl' => false,
        ],
        [
            'code' => 'es-419',
            'label' => 'Latin American Spanish',
            'native' => 'Español (Latinoamérica)',
            'flag' => '🇲🇽',
            'rtl' => false,
        ],
        [
            'code' => 'fr-CA',
            'label' => 'Canadian French',
            'native' => 'Français (Canada)',
            'flag' => '🇨🇦',
            'rtl' => false,
        ],
        [
            'code' => 'de-AT',
            'label' => 'Austrian German',
            'native' => 'Deutsch (Österreich)',
            'flag' => '🇦🇹',
            'rtl' => false,
        ],
        [
            'code' => 'de-CH',
            'label' => 'Swiss Standard German',
            'native' => 'Deutsch (Schweiz)',
            'flag' => '🇨🇭',
            'rtl' => false,
        ],
        ['code' => 'nl-BE', 'label' => 'Flemish', 'native' => 'Vlaams', 'flag' => '🇧🇪', 'rtl' => false],
        ['code' => 'zh-HK', 'label' => 'Hong Kong Chinese', 'native' => '繁體中文（香港）', 'flag' => '🇭🇰', 'rtl' => false],
        ['code' => 'yue', 'label' => 'Cantonese', 'native' => '粵語', 'flag' => '🇭🇰', 'rtl' => false],
        ['code' => 'nb', 'label' => 'Norwegian Bokmål', 'native' => 'Norsk bokmål', 'flag' => '🇳🇴', 'rtl' => false],
        ['code' => 'nn', 'label' => 'Norwegian Nynorsk', 'native' => 'Norsk nynorsk', 'flag' => '🇳🇴', 'rtl' => false],
        ['code' => 'sr', 'label' => 'Serbian', 'native' => 'Српски', 'flag' => '🇷🇸', 'rtl' => false],
        [
            'code' => 'sr-Latn',
            'label' => 'Serbian (Latin)',
            'native' => 'Srpski (latinica)',
            'flag' => '🇷🇸',
            'rtl' => false,
        ],
        ['code' => 'ar-EG', 'label' => 'Egyptian Arabic', 'native' => 'العربية (مصر)', 'flag' => '🇪🇬', 'rtl' => true],
        [
            'code' => 'ar-MA',
            'label' => 'Moroccan Arabic',
            'native' => 'الدارجة المغربية',
            'flag' => '🇲🇦',
            'rtl' => true,
        ],
        ['code' => 'sk', 'label' => 'Slovak', 'native' => 'Slovenčina', 'flag' => '🇸🇰', 'rtl' => false],
        ['code' => 'sl', 'label' => 'Slovenian', 'native' => 'Slovenščina', 'flag' => '🇸🇮', 'rtl' => false],
        ['code' => 'hr', 'label' => 'Croatian', 'native' => 'Hrvatski', 'flag' => '🇭🇷', 'rtl' => false],
        ['code' => 'bs', 'label' => 'Bosnian', 'native' => 'Bosanski', 'flag' => '🇧🇦', 'rtl' => false],
        ['code' => 'cnr', 'label' => 'Montenegrin', 'native' => 'Crnogorski', 'flag' => '🇲🇪', 'rtl' => false],
        ['code' => 'mk', 'label' => 'Macedonian', 'native' => 'Македонски', 'flag' => '🇲🇰', 'rtl' => false],
        ['code' => 'bg', 'label' => 'Bulgarian', 'native' => 'Български', 'flag' => '🇧🇬', 'rtl' => false],
        ['code' => 'be', 'label' => 'Belarusian', 'native' => 'Беларуская', 'flag' => '🇧🇾', 'rtl' => false],
        ['code' => 'hsb', 'label' => 'Upper Sorbian', 'native' => 'Hornjoserbšćina', 'flag' => '🇩🇪', 'rtl' => false],
        ['code' => 'rue', 'label' => 'Rusyn', 'native' => 'Русиньскый', 'flag' => '🇸🇰', 'rtl' => false],
        ['code' => 'lt', 'label' => 'Lithuanian', 'native' => 'Lietuvių', 'flag' => '🇱🇹', 'rtl' => false],
        ['code' => 'lv', 'label' => 'Latvian', 'native' => 'Latviešu', 'flag' => '🇱🇻', 'rtl' => false],
        ['code' => 'et', 'label' => 'Estonian', 'native' => 'Eesti', 'flag' => '🇪🇪', 'rtl' => false],
        ['code' => 'se', 'label' => 'Northern Sami', 'native' => 'Davvisámegiella', 'flag' => '🇳🇴', 'rtl' => false],
        ['code' => 'is', 'label' => 'Icelandic', 'native' => 'Íslenska', 'flag' => '🇮🇸', 'rtl' => false],
        ['code' => 'fo', 'label' => 'Faroese', 'native' => 'Føroyskt', 'flag' => '🇫🇴', 'rtl' => false],
        ['code' => 'kl', 'label' => 'Greenlandic', 'native' => 'Kalaallisut', 'flag' => '🇬🇱', 'rtl' => false],
        ['code' => 'ga', 'label' => 'Irish', 'native' => 'Gaeilge', 'flag' => '🇮🇪', 'rtl' => false],
        ['code' => 'gd', 'label' => 'Scottish Gaelic', 'native' => 'Gàidhlig', 'flag' => '🇬🇧', 'rtl' => false],
        ['code' => 'cy', 'label' => 'Welsh', 'native' => 'Cymraeg', 'flag' => '🇬🇧', 'rtl' => false],
        ['code' => 'kw', 'label' => 'Cornish', 'native' => 'Kernewek', 'flag' => '🇬🇧', 'rtl' => false],
        ['code' => 'gv', 'label' => 'Manx', 'native' => 'Gaelg', 'flag' => '🇮🇲', 'rtl' => false],
        ['code' => 'br', 'label' => 'Breton', 'native' => 'Brezhoneg', 'flag' => '🇫🇷', 'rtl' => false],
        ['code' => 'eu', 'label' => 'Basque', 'native' => 'Euskara', 'flag' => '🇪🇸', 'rtl' => false],
        ['code' => 'gl', 'label' => 'Galician', 'native' => 'Galego', 'flag' => '🇪🇸', 'rtl' => false],
        ['code' => 'ast', 'label' => 'Asturian', 'native' => 'Asturianu', 'flag' => '🇪🇸', 'rtl' => false],
        ['code' => 'an', 'label' => 'Aragonese', 'native' => 'Aragonés', 'flag' => '🇪🇸', 'rtl' => false],
        ['code' => 'oc', 'label' => 'Occitan', 'native' => 'Occitan', 'flag' => '🇫🇷', 'rtl' => false],
        ['code' => 'co', 'label' => 'Corsican', 'native' => 'Corsu', 'flag' => '🇫🇷', 'rtl' => false],
        ['code' => 'sc', 'label' => 'Sardinian', 'native' => 'Sardu', 'flag' => '🇮🇹', 'rtl' => false],
        ['code' => 'fur', 'label' => 'Friulian', 'native' => 'Furlan', 'flag' => '🇮🇹', 'rtl' => false],
        ['code' => 'rm', 'label' => 'Romansh', 'native' => 'Rumantsch', 'flag' => '🇨🇭', 'rtl' => false],
        [
            'code' => 'gsw',
            'label' => 'Alemannic German',
            'native' => 'Schwiizerdütsch',
            'flag' => '🇨🇭',
            'rtl' => false,
        ],
        ['code' => 'lb', 'label' => 'Luxembourgish', 'native' => 'Lëtzebuergesch', 'flag' => '🇱🇺', 'rtl' => false],
        ['code' => 'nds', 'label' => 'Low German', 'native' => 'Plattdüütsch', 'flag' => '🇩🇪', 'rtl' => false],
        ['code' => 'bar', 'label' => 'Bavarian', 'native' => 'Boarisch', 'flag' => '🇩🇪', 'rtl' => false],
        ['code' => 'fy', 'label' => 'Western Frisian', 'native' => 'Frysk', 'flag' => '🇳🇱', 'rtl' => false],
        ['code' => 'li', 'label' => 'Limburgish', 'native' => 'Limburgs', 'flag' => '🇳🇱', 'rtl' => false],
        ['code' => 'wa', 'label' => 'Walloon', 'native' => 'Walon', 'flag' => '🇧🇪', 'rtl' => false],
        ['code' => 'mt', 'label' => 'Maltese', 'native' => 'Malti', 'flag' => '🇲🇹', 'rtl' => false],
        ['code' => 'sq', 'label' => 'Albanian', 'native' => 'Shqip', 'flag' => '🇦🇱', 'rtl' => false],
        ['code' => 'la', 'label' => 'Latin', 'native' => 'Latina', 'flag' => '🇻🇦', 'rtl' => false],
        ['code' => 'eo', 'label' => 'Esperanto', 'native' => 'Esperanto', 'flag' => '🇪🇺', 'rtl' => false],
        ['code' => 'yi', 'label' => 'Yiddish', 'native' => 'ייִדיש', 'flag' => '🇮🇱', 'rtl' => true],
        ['code' => 'hy', 'label' => 'Armenian', 'native' => 'Հայերեն', 'flag' => '🇦🇲', 'rtl' => false],
        ['code' => 'ka', 'label' => 'Georgian', 'native' => 'ქართული', 'flag' => '🇬🇪', 'rtl' => false],
        ['code' => 'os', 'label' => 'Ossetian', 'native' => 'Ирон æвзаг', 'flag' => '🇬🇪', 'rtl' => false],
        ['code' => 'ab', 'label' => 'Abkhaz', 'native' => 'Аԥсшәа', 'flag' => '🇬🇪', 'rtl' => false],
        ['code' => 'ce', 'label' => 'Chechen', 'native' => 'Нохчийн мотт', 'flag' => '🇷🇺', 'rtl' => false],
        ['code' => 'az', 'label' => 'Azerbaijani', 'native' => 'Azərbaycan dili', 'flag' => '🇦🇿', 'rtl' => false],
        ['code' => 'kk', 'label' => 'Kazakh', 'native' => 'Қазақ тілі', 'flag' => '🇰🇿', 'rtl' => false],
        ['code' => 'ky', 'label' => 'Kyrgyz', 'native' => 'Кыргызча', 'flag' => '🇰🇬', 'rtl' => false],
        ['code' => 'uz', 'label' => 'Uzbek', 'native' => 'Oʻzbekcha', 'flag' => '🇺🇿', 'rtl' => false],
        ['code' => 'tk', 'label' => 'Turkmen', 'native' => 'Türkmençe', 'flag' => '🇹🇲', 'rtl' => false],
        ['code' => 'tt', 'label' => 'Tatar', 'native' => 'Татар теле', 'flag' => '🇷🇺', 'rtl' => false],
        ['code' => 'ba', 'label' => 'Bashkir', 'native' => 'Башҡортса', 'flag' => '🇷🇺', 'rtl' => false],
        ['code' => 'cv', 'label' => 'Chuvash', 'native' => 'Чӑвашла', 'flag' => '🇷🇺', 'rtl' => false],
        ['code' => 'sah', 'label' => 'Yakut', 'native' => 'Саха тыла', 'flag' => '🇷🇺', 'rtl' => false],
        ['code' => 'ug', 'label' => 'Uyghur', 'native' => 'ئۇيغۇرچە', 'flag' => '🇨🇳', 'rtl' => true],
        ['code' => 'mn', 'label' => 'Mongolian', 'native' => 'Монгол хэл', 'flag' => '🇲🇳', 'rtl' => false],
        ['code' => 'bo', 'label' => 'Tibetan', 'native' => 'བོད་སྐད་', 'flag' => '🇨🇳', 'rtl' => false],
        ['code' => 'dz', 'label' => 'Dzongkha', 'native' => 'རྫོང་ཁ', 'flag' => '🇧🇹', 'rtl' => false],
        ['code' => 'fa-AF', 'label' => 'Dari', 'native' => 'دری', 'flag' => '🇦🇫', 'rtl' => true],
        ['code' => 'ps', 'label' => 'Pashto', 'native' => 'پښتو', 'flag' => '🇦🇫', 'rtl' => true],
        ['code' => 'ku', 'label' => 'Kurmanji Kurdish', 'native' => 'Kurmancî', 'flag' => '🇹🇷', 'rtl' => false],
        ['code' => 'ckb', 'label' => 'Sorani Kurdish', 'native' => 'کوردیی ناوەندی', 'flag' => '🇮🇶', 'rtl' => true],
        ['code' => 'syr', 'label' => 'Syriac', 'native' => 'ܣܘܪܝܝܐ', 'flag' => '🇮🇶', 'rtl' => true],
        ['code' => 'te', 'label' => 'Telugu', 'native' => 'తెలుగు', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'mr', 'label' => 'Marathi', 'native' => 'मराठी', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'gu', 'label' => 'Gujarati', 'native' => 'ગુજરાતી', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'kn', 'label' => 'Kannada', 'native' => 'ಕನ್ನಡ', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'ml', 'label' => 'Malayalam', 'native' => 'മലയാളം', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'or', 'label' => 'Odia', 'native' => 'ଓଡ଼ିଆ', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'pa', 'label' => 'Punjabi', 'native' => 'ਪੰਜਾਬੀ', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'pa-Arab', 'label' => 'Western Punjabi', 'native' => 'پنجابی', 'flag' => '🇵🇰', 'rtl' => true],
        ['code' => 'as', 'label' => 'Assamese', 'native' => 'অসমীয়া', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'mai', 'label' => 'Maithili', 'native' => 'मैथिली', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'bho', 'label' => 'Bhojpuri', 'native' => 'भोजपुरी', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'sat', 'label' => 'Santali', 'native' => 'ᱥᱟᱱᱛᱟᱲᱤ', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'ks', 'label' => 'Kashmiri', 'native' => 'کٲشُر', 'flag' => '🇮🇳', 'rtl' => true],
        ['code' => 'sa', 'label' => 'Sanskrit', 'native' => 'संस्कृतम्', 'flag' => '🇮🇳', 'rtl' => false],
        ['code' => 'ne', 'label' => 'Nepali', 'native' => 'नेपाली', 'flag' => '🇳🇵', 'rtl' => false],
        ['code' => 'si', 'label' => 'Sinhala', 'native' => 'සිංහල', 'flag' => '🇱🇰', 'rtl' => false],
        ['code' => 'sd', 'label' => 'Sindhi', 'native' => 'سنڌي', 'flag' => '🇵🇰', 'rtl' => true],
        ['code' => 'dv', 'label' => 'Divehi', 'native' => 'ދިވެހި', 'flag' => '🇲🇻', 'rtl' => true],
        ['code' => 'km', 'label' => 'Khmer', 'native' => 'ភាសាខ្មែរ', 'flag' => '🇰🇭', 'rtl' => false],
        ['code' => 'lo', 'label' => 'Lao', 'native' => 'ລາວ', 'flag' => '🇱🇦', 'rtl' => false],
        ['code' => 'my', 'label' => 'Burmese', 'native' => 'မြန်မာဘာသာ', 'flag' => '🇲🇲', 'rtl' => false],
        ['code' => 'jv', 'label' => 'Javanese', 'native' => 'Basa Jawa', 'flag' => '🇮🇩', 'rtl' => false],
        ['code' => 'su', 'label' => 'Sundanese', 'native' => 'Basa Sunda', 'flag' => '🇮🇩', 'rtl' => false],
        ['code' => 'fil', 'label' => 'Filipino', 'native' => 'Filipino', 'flag' => '🇵🇭', 'rtl' => false],
        ['code' => 'tl', 'label' => 'Tagalog', 'native' => 'Tagalog', 'flag' => '🇵🇭', 'rtl' => false],
        ['code' => 'ceb', 'label' => 'Cebuano', 'native' => 'Binisaya', 'flag' => '🇵🇭', 'rtl' => false],
        ['code' => 'ilo', 'label' => 'Ilocano', 'native' => 'Ilokano', 'flag' => '🇵🇭', 'rtl' => false],
        ['code' => 'war', 'label' => 'Waray', 'native' => 'Winaray', 'flag' => '🇵🇭', 'rtl' => false],
        ['code' => 'sw', 'label' => 'Swahili', 'native' => 'Kiswahili', 'flag' => '🇰🇪', 'rtl' => false],
        ['code' => 'am', 'label' => 'Amharic', 'native' => 'አማርኛ', 'flag' => '🇪🇹', 'rtl' => false],
        ['code' => 'ti', 'label' => 'Tigrinya', 'native' => 'ትግርኛ', 'flag' => '🇪🇷', 'rtl' => false],
        ['code' => 'om', 'label' => 'Oromo', 'native' => 'Afaan Oromoo', 'flag' => '🇪🇹', 'rtl' => false],
        ['code' => 'so', 'label' => 'Somali', 'native' => 'Soomaali', 'flag' => '🇸🇴', 'rtl' => false],
        ['code' => 'ha', 'label' => 'Hausa', 'native' => 'Hausa', 'flag' => '🇳🇬', 'rtl' => false],
        ['code' => 'yo', 'label' => 'Yoruba', 'native' => 'Yorùbá', 'flag' => '🇳🇬', 'rtl' => false],
        ['code' => 'ig', 'label' => 'Igbo', 'native' => 'Igbo', 'flag' => '🇳🇬', 'rtl' => false],
        ['code' => 'af', 'label' => 'Afrikaans', 'native' => 'Afrikaans', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 'zu', 'label' => 'Zulu', 'native' => 'isiZulu', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 'xh', 'label' => 'Xhosa', 'native' => 'isiXhosa', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 'st', 'label' => 'Sesotho', 'native' => 'Sesotho', 'flag' => '🇱🇸', 'rtl' => false],
        ['code' => 'nso', 'label' => 'Sepedi', 'native' => 'Sepedi', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 'tn', 'label' => 'Setswana', 'native' => 'Setswana', 'flag' => '🇧🇼', 'rtl' => false],
        ['code' => 'ts', 'label' => 'Xitsonga', 'native' => 'Xitsonga', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 've', 'label' => 'Tshivenda', 'native' => 'Tshivenḓa', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 'ss', 'label' => 'Swati', 'native' => 'siSwati', 'flag' => '🇸🇿', 'rtl' => false],
        ['code' => 'nr', 'label' => 'Southern Ndebele', 'native' => 'isiNdebele', 'flag' => '🇿🇦', 'rtl' => false],
        ['code' => 'sn', 'label' => 'Shona', 'native' => 'chiShona', 'flag' => '🇿🇼', 'rtl' => false],
        ['code' => 'ny', 'label' => 'Chichewa', 'native' => 'Chichewa', 'flag' => '🇲🇼', 'rtl' => false],
        ['code' => 'rw', 'label' => 'Kinyarwanda', 'native' => 'Ikinyarwanda', 'flag' => '🇷🇼', 'rtl' => false],
        ['code' => 'rn', 'label' => 'Kirundi', 'native' => 'Ikirundi', 'flag' => '🇧🇮', 'rtl' => false],
        ['code' => 'lg', 'label' => 'Luganda', 'native' => 'Luganda', 'flag' => '🇺🇬', 'rtl' => false],
        ['code' => 'ln', 'label' => 'Lingala', 'native' => 'Lingála', 'flag' => '🇨🇩', 'rtl' => false],
        ['code' => 'kg', 'label' => 'Kikongo', 'native' => 'Kikongo', 'flag' => '🇨🇩', 'rtl' => false],
        ['code' => 'wo', 'label' => 'Wolof', 'native' => 'Wolof', 'flag' => '🇸🇳', 'rtl' => false],
        ['code' => 'ff', 'label' => 'Fula', 'native' => 'Pulaar', 'flag' => '🇸🇳', 'rtl' => false],
        ['code' => 'bm', 'label' => 'Bambara', 'native' => 'Bamanankan', 'flag' => '🇲🇱', 'rtl' => false],
        ['code' => 'ak', 'label' => 'Akan', 'native' => 'Akan', 'flag' => '🇬🇭', 'rtl' => false],
        ['code' => 'tw', 'label' => 'Twi', 'native' => 'Twi', 'flag' => '🇬🇭', 'rtl' => false],
        ['code' => 'ee', 'label' => 'Ewe', 'native' => 'Eʋegbe', 'flag' => '🇬🇭', 'rtl' => false],
        ['code' => 'mg', 'label' => 'Malagasy', 'native' => 'Malagasy', 'flag' => '🇲🇬', 'rtl' => false],
        ['code' => 'kab', 'label' => 'Kabyle', 'native' => 'Taqbaylit', 'flag' => '🇩🇿', 'rtl' => false],
        ['code' => 'tzm', 'label' => 'Tamazight', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'flag' => '🇲🇦', 'rtl' => false],
        ['code' => 'sg', 'label' => 'Sango', 'native' => 'Sängö', 'flag' => '🇨🇫', 'rtl' => false],
        ['code' => 'ht', 'label' => 'Haitian Creole', 'native' => 'Kreyòl ayisyen', 'flag' => '🇭🇹', 'rtl' => false],
        ['code' => 'pap', 'label' => 'Papiamento', 'native' => 'Papiamentu', 'flag' => '🇦🇼', 'rtl' => false],
        ['code' => 'srn', 'label' => 'Sranan Tongo', 'native' => 'Sranantongo', 'flag' => '🇸🇷', 'rtl' => false],
        ['code' => 'qu', 'label' => 'Quechua', 'native' => 'Runa Simi', 'flag' => '🇵🇪', 'rtl' => false],
        ['code' => 'gn', 'label' => 'Guarani', 'native' => 'Avañe\'ẽ', 'flag' => '🇵🇾', 'rtl' => false],
        ['code' => 'ay', 'label' => 'Aymara', 'native' => 'Aymar aru', 'flag' => '🇧🇴', 'rtl' => false],
        ['code' => 'nah', 'label' => 'Nahuatl', 'native' => 'Nāhuatl', 'flag' => '🇲🇽', 'rtl' => false],
        ['code' => 'chr', 'label' => 'Cherokee', 'native' => 'ᏣᎳᎩ', 'flag' => '🇺🇸', 'rtl' => false],
        ['code' => 'nv', 'label' => 'Navajo', 'native' => 'Diné bizaad', 'flag' => '🇺🇸', 'rtl' => false],
        ['code' => 'iu', 'label' => 'Inuktitut', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'flag' => '🇨🇦', 'rtl' => false],
        ['code' => 'mi', 'label' => 'Maori', 'native' => 'Te reo Māori', 'flag' => '🇳🇿', 'rtl' => false],
        ['code' => 'sm', 'label' => 'Samoan', 'native' => 'Gagana Sāmoa', 'flag' => '🇼🇸', 'rtl' => false],
        ['code' => 'to', 'label' => 'Tongan', 'native' => 'Lea faka-Tonga', 'flag' => '🇹🇴', 'rtl' => false],
        ['code' => 'fj', 'label' => 'Fijian', 'native' => 'Na Vosa Vakaviti', 'flag' => '🇫🇯', 'rtl' => false],
        ['code' => 'haw', 'label' => 'Hawaiian', 'native' => 'ʻŌlelo Hawaiʻi', 'flag' => '🇺🇸', 'rtl' => false],
        ['code' => 'ty', 'label' => 'Tahitian', 'native' => 'Reo Tahiti', 'flag' => '🇵🇫', 'rtl' => false],
        ['code' => 'ch', 'label' => 'Chamorro', 'native' => 'Chamoru', 'flag' => '🇬🇺', 'rtl' => false],
        ['code' => 'mh', 'label' => 'Marshallese', 'native' => 'Kajin M̧ajeļ', 'flag' => '🇲🇭', 'rtl' => false],
        ['code' => 'tpi', 'label' => 'Tok Pisin', 'native' => 'Tok Pisin', 'flag' => '🇵🇬', 'rtl' => false],
    ];
}
